  
http://localhost:3000/products

###

GET http://localhost:3000/products/1

###

POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "title": "Fritadeira Elétrica sem Óleo Mondial",
    "value": "499",
    "photo": "../../../assets/produto-00001.webp"
}

###

PUT http://localhost:3000/products/2 HTTP/1.1
content-type: application/json

{
    "title": "BLACK+DECKER Ferro de Passar 1800W Preto 220V",
    "value": "499",
    "photo": "../../../assets/produto-00002.webp"
}

###

DELETE http://localhost:3000/products/2